# Generated by Django 4.0.3 on 2022-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('chevaux', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
