# Generated by Django 4.0.3 on 2022-05-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudMarque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marque',
            old_name='marque',
            new_name='nom',
        ),
    ]
