# Generated by Django 4.0.3 on 2022-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudMarque', '0002_rename_marque_marque_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='chevaux',
            field=models.IntegerField(blank=True),
        ),
    ]
